apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
  namespace: converter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request storage size
