apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  namespace: converter
spec:
  capacity:
    storage: 1Gi # Size of the storage
  accessModes:
    - ReadWriteOnce # Only one pod can write
  hostPath:
    path: /mnt/data/uploads # Local directory on the Kubernetes node (for testing purposes)
