apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: converter
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: converter
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 5672 # Internal RabbitMQ Broker Port
      targetPort: 5672 # Container RabbitMQ Broker Port
      protocol: TCP
      nodePort: 31672 # NodePort for accessing RabbitMQ Broker
      name: amqp
    - port: 15672 # Internal RabbitMQ Management UI Port
      targetPort: 15672 # Container Management UI Port
      protocol: TCP
      nodePort: 31673 # NodePort for accessing Management UI
      name: management
  selector:
    app: rabbitmq
