spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

storage:
  location: ${STORAGE_LOCATION:${user.home}/DocxToPdf/uploads}

queue:
  conversion:
    name: ${CONVERSION_QUEUE_NAME:docx-pdf-conversion-queue}
